# Generated by Django 5.1.1 on 2024-11-20 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fard_Salah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salah', models.CharField(max_length=100, unique=True)),
                ('rakat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('azan', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('jamath', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
